version: '3'

services:

  historical:
    image: $IMAGE_NAME
    container_name: $CONTAINER_NAME
    ports: 
      - 8087:8087
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6.17
    container_name: mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - /home/jc/database/mongo/db:/data/db
      - /home/jc/database/mongo/configdb:/data/configdb
    ports:
      - 27017:27017

networks:
  default:
    external:
      name: cluster-network